apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: retail-system-swd-backend
  name: retail-system-swd-backend
  namespace: retail-system-swd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-system-swd-backend
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: retail-system-swd-backend
    spec:
      containers:
      - image: blackheat/retail-system-swd:build-20191216101146
        name: retail-system-swd-backend
        env:
        - name: SQLSERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: retail-system-swd-backend
              key: sqlserver-host
        - name: SQLSERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: retail-system-swd-backend
              key: sqlserver-port
        - name: SQLSERVER_USERNAME
          valueFrom:
            configMapKeyRef:
              name: retail-system-swd-backend
              key: sqlserver-username
        - name: SQLSERVER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: retail-system-swd-backend
              key: sqlserver-password
        - name: SQLSERVER_DBNAME
          valueFrom:
            configMapKeyRef:
              name: retail-system-swd-backend
              key: sqlserver-dbname
status: {}